Upscale MacOS fix
GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon pull request #254
Opened 2021-04-07 10:32 UTC by bnagirniak

### PURPOSE
Viewport upscaling doesn't work good on MacOS. This PR should fix #241 .

### EFFECT OF CHANGE
Fixed viewport upscaling on MacOS.

### TECHNICAL STEPS
Changed upscaling mode from best to fast.

### NOTES FOR REVIEWERS
 Upscaling should use FAST mode at all systems, not only MacOS. This is recommendation from RIF team.

2021-04-07 13:38 UTC, bsavery requested changes
Should this revert the other change that disables on macOS?

2021-04-07 14:37 UTC, bnagirniak commented
Just checked, fix #244 exists only in master branch, not in develop, therefore I merged master branch here for reverting disabling upscale on MacOS.

2021-04-07 14:44 UTC, bsavery commented
Oops.  That was my bad with the pull request for the other.

2021-04-19 10:34 UTC, ardraeiss approved these changes

2021-04-19 13:47 UTC, merged