Updated RIF library to version 1.7.1
GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon pull request #283
Opened 2021-06-04 13:58 UTC by ardraeiss

### PURPOSE
Updated RIF library to the version 1.7.1

### EFFECT OF CHANGE
- updated RIF library to the version 1.7.1;
- fixed issue with Viewport Upscale mode getting incorrect results near the bright areas.

### TECHNICAL STEPS
- updated RIF submodule to the commit with 1.7.1;
- used useHDR flag for viewport Upscale filter.

2021-06-04 14:37 UTC, bnagirniak approved these changes

2021-06-08 07:48 UTC, Dizzyspb approved these changes
RIF 1.7.1 integration is tested by QA. Approved for merge.

2021-06-08 14:59 UTC, bsavery requested changes
Can we enable viewport upscale on macOS now?

2021-06-08 20:36 UTC, ardraeiss commented
> Can we enable viewport upscale on macOS now?

The upscale disable on MacOS appeared to be "master branch only" change

2021-06-08 20:49 UTC, merged