RPRBLND-1644: Principled BSDF Emission Strength not working with RPR
GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon pull request #335
Opened 2021-07-19 12:22 UTC by VascoPi

### PURPOSE
Make Emission Strength in Principled BSDF work as expected. Add support for a value >1.

### EFFECT OF CHANGE
Added Emission Strength support for Principled BSDF.

### TECHNICAL STEPS
Added Emission Strength param support for ShaderNodeBsdfPrincipled, now RPR supports a value >1.
Now MATERIAL_INPUT_UBER_EMISSION_COLOR takes into account emission and emission strength.

2021-07-19 14:39 UTC, bsavery reviewed
So this is more of a question than a review.  I'd like to see you justify the math here.  Internally RPR does emission color * emission strength.  

So as far as I can see, we will actually multiply the emission color * emission strength twice here?  

Secondly emission seems to be minimum of 1?  what if strength is .5?

2021-07-19 16:26 UTC, VascoPi commented
> So this is more of a question than a review. I'd like to see you justify the math here. Internally RPR does emission color * emission strength.

As I see ShaderNodeBsdfPrincipled uses these two inputs for emission part of the shader.
MATERIAL_INPUT_UBER_EMISSION_WEIGHT - emission_weight, transition between emission and diffuse (0.0 to 1.0), for example at a value 0.0 - 0.5 material still catches some shadows/reflections and so on. It's clamped internally, so the max value is 1.0. Same in Uber Shader.
So I decoded to use color input also for emission_sterngth.
MATERIAL_INPUT_UBER_EMISSION_COLOR - emission * emission_strength. I make the math to input color value and emission strength.

>So as far as I can see, we will actually multiply the emission color * emission strength twice here?

Yes, thanks, will fix it.

2021-07-20 08:45 UTC, bnagirniak requested changes
Optimization and blender version check is required

2021-07-20 08:45 UTC, bnagirniak commented on src/rprblender/nodes/blender_nodes.py
> +        emission_strength = self.get_input_value('Emission Strength')
Add `if enabled(emission):` and blender version check here

2021-07-20 08:45 UTC, bnagirniak commented on src/rprblender/nodes/blender_nodes.py
> +            emission_weight = (emission).average_xyz().min(1.0) * 0.5 + 0.5
just emission.average_xyz

2021-07-20 10:29 UTC, bnagirniak approved these changes
Tested - works good

2021-07-20 14:21 UTC, bsavery commented
@ARozghon please test functionality

2021-07-21 19:06 UTC, DagerD approved these changes
Tested. Works ok.

2021-07-21 19:16 UTC, ARozghon commented
approve from QA, all works fine and we get the correct autotest results

2021-07-21 20:49 UTC, merged