RPRBLND-1887: Error crashing with wave texture.
GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon pull request #367
Opened 2021-10-01 08:04 UTC by DagerD

### PURPOSE
If object has vast number of faces it consumption a lot of memory and blender hangs.

### EFFECT OF CHANGE
Added warning if object has more than 1 000 000 faces.

### TECHNICAL STEPS
Added check in objects sync.

2021-10-01 14:48 UTC, bnagirniak requested changes
Commented in code

2021-10-01 14:48 UTC, bnagirniak commented on src/rprblender/export/object.py
> +                 f'Consider simplifying geometry to less than 1 000 000 faces')
I think this overall check should be moved to mesh.py. Also set 1000000 as constant

2021-10-04 08:43 UTC, bnagirniak approved these changes

2021-10-04 08:43 UTC, bnagirniak commented on src/rprblender/export/mesh.py
> +                 f'Consider simplifying geometry to less than 1 000 000 faces')
change 1000000 to {FACES_LARGE_AMOUNT:,}

2021-10-04 08:48 UTC, bnagirniak commented on src/rprblender/export/mesh.py
> +        log.warn(f'Found object {obj.name_full} with {len(obj.data.polygons)} faces. '
Move this warn to MeshData.init...

2021-10-04 13:59 UTC, bnagirniak approved these changes

2021-10-05 10:05 UTC, VascoPi approved these changes
Tested, work well.

2021-10-05 12:48 UTC, bnagirniak approved these changes
Tested - works good

2021-10-05 16:16 UTC, bsavery commented on src/rprblender/export/mesh.py
> +TRIANGLES_LARGE_AMOUNT = 1000000
Please rename this to 
"EXCESS_TRIANGLES_THRESHOLD"

2021-10-05 16:18 UTC, bsavery commented
This is a random thought.  Is the error coming in RPR or in creating the numpy array?  Is it possible you're overflowing number of max int indices in the array?

2021-10-06 07:25 UTC, DagerD commented
> This is a random thought. Is the error coming in RPR or in creating the numpy array? Is it possible you're overflowing number of max int indices in the array?

There is no error, only extremely long syncing of objects with big amount of triangles.

2021-10-06 16:19 UTC, merged