RPRBLND-1822: Baikal Next support
GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon pull request #411
Opened 2021-12-02 16:16 UTC by VascoPi

### PURPOSE
Implement Baikal Next support.

### EFFECT OF CHANGE
Added render quality HybridPro.

### TECHNICAL STEPS
Name convention BaikalNext as HybridPro
Implementation based on Hybrid
Added HybridPro to render property panel in quality section
Temporary added file HybridPro.dll
Temporary added file HybridPro.so
Added new export_hybrydpro() for nodes, temporary uses export_hybryd()
Added new modules animation_engine_hybridpro.py, viewport_engine_hybridpro.py, render_engine_hybridpro.py, context_hybridpro.py
Added class registration for RenderEngineHybridPro, ViewportEngineHybridPro, AnimationEngineHybridPro
Added various additional checks for HybridPro

### NOTES FOR REVIEWERS
Need to be updated at least to core 2.2.9

2021-12-03 00:35 UTC, bsavery commented on src/rprblender/properties/render.py
> +            ('HYBRIDPRO', "HybridPro", "HYBRIDPRO render quality using BaikalNext, only hardware ray tracing support")
Name should be RPR Interactive
Northstar is now named "RPR Final"

2021-12-07 10:39 UTC, bnagirniak approved these changes
Added some improvements to naming and disabled hybrid render qualities if hybridpro when hybridpro is enabled.

2021-12-07 14:17 UTC, DagerD requested changes
I still have "Interactive" option in Render Quality and in doesn't work for me (5700 xt).
![image](https://user-images.githubusercontent.com/42409851/145045511-c191c78b-b8a4-4345-9651-94d0b16fe07c.png)

2021-12-07 22:50 UTC, bsavery commented
> I still have "Interactive" option in Render Quality and in doesn't work for me (5700 xt).
> ![image](https://user-images.githubusercontent.com/42409851/145045511-c191c78b-b8a4-4345-9651-94d0b16fe07c.png)

RPR - Interactive is only supported on GPUs with Hardware raytracing.  

We should still keep low - medium -high

2021-12-08 10:28 UTC, DagerD approved these changes
Fixed.

2021-12-09 16:06 UTC, VascoPi commented
Problems with core2.2.10.
These two pictures were made with core2.2.9 and 2.2.10(failed), no errors. Waiting responde from HybridPro developers.
![image](https://user-images.githubusercontent.com/42581166/145431971-c5f5bd94-17a5-4f97-b790-81c4112e10a8.png)
![blender_attmyy9wxr_720](https://user-images.githubusercontent.com/42581166/145431977-aa04dfe5-5d06-4014-a8ce-d9ff2e7c44a1.png)

2021-12-10 09:48 UTC, bnagirniak commented
I confirm, with new core all materials in HybridPro are pink now, seems usual materials aren't supported now.
![image](https://user-images.githubusercontent.com/33626169/145553634-08af596d-46ae-47b1-b0e4-c49d69d8023b.png)

2021-12-10 18:38 UTC, bsavery commented
The should be supported.

2021-12-14 10:20 UTC, bnagirniak approved these changes
Tested - now HybridPro works as expected.

2021-12-15 00:29 UTC, merged