RPRBLND-2079: Blender crash with AOV and Hybrid Pro
GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon pull request #481
Opened 2022-04-07 18:28 UTC by VascoPi

### PURPOSE
Blender crash with AOV and Hybrid Pro.

### EFFECT OF CHANGE
RPR Passe panel shows only AOVs that are supported by the current Render Quality.

### TECHNICAL STEPS
Added 'hybrindpro' key to aovs_info, describes the support of pass by HybridPro engine.
Improved RPR_VIEWLAYER_PT_aovs, do_register_pass ,  export_aovs with the condition.
Small code improvements.

2022-04-08 15:17 UTC, bsavery commented
IMO this should be handled at the RPR / Hybrid pro level, NOT worked around in the plugin code, as this leads to ugly solutions that never get fixed.  

Or at worst done in the RPR python binding for hybrid.

2022-04-11 08:38 UTC, bnagirniak requested changes
Add warning with unsupported AOV in hybridpro

2022-04-11 08:38 UTC, bnagirniak commented on src/rprblender/properties/view_layer.py
> +            'hybridpro': True
instead of adding 'hybridpro' option better all list variable with unsupported AOVs in pyhybridpro.py

2022-04-11 14:50 UTC, VascoPi commented
Oh I understand, I'll make another solution. Reported trace to HybridPro team, I wait for feedback.

2022-04-18 16:27 UTC, VascoPi commented
Moved to https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/pull/486

2022-04-18 16:27 UTC, closed without merging