RPRBLND-2177: HybridPro add multimaterial support
GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon pull request #534
Opened 2022-07-05 15:45 UTC by VascoPi

### PURPOSE
Add multimaterial support to HybridPro.

### EFFECT OF CHANGE
Added support of multimaterial for Interactive render mode.

### TECHNICAL STEPS
Improved set_material_faces method in pyhybridpro.py module.
Enabled CONTEXT_CREATEPROP_HYBRID_ENABLE_PER_FACE_MATERIALS parameter. It should be set within context creation.
Added has_multimaterial_object variable for optimization purposes.

2022-07-07 13:23 UTC, VascoPi commented
Discussed with HybridPro team, so let's wait for [PR-910](https://github.com/Radeon-Pro/RPRHybrid/pull/910).
It should bring some improvements related to the issues being noticed within testing.

2022-07-20 10:09 UTC, VascoPi commented
Expected to be fixed with core 2.2.16

2022-07-21 07:45 UTC, ARozghon reviewed
waiting for core 2.2.16

2022-10-07 17:08 UTC, DagerD approved these changes
Tested. Works ok.

2022-10-07 18:08 UTC, bsavery approved these changes

2022-10-18 08:57 UTC, VascoPi commented
1 sample
![blender_1dtZcEMTSh](https://user-images.githubusercontent.com/42581166/196384999-808d7d6f-7f63-4a9b-abd6-17aba22e2ad0.png)

5 samples
![blender_iJOob9gid5](https://user-images.githubusercontent.com/42581166/196385042-6b51bd6d-c8a8-4d6b-b556-c579248345ed.png)

20 samples
![blender_jCqUynD7CM](https://user-images.githubusercontent.com/42581166/196385180-d2da283d-15eb-4833-a2f7-1c61d942d67a.png)

2022-10-27 15:40 UTC, bsavery requested changes

2022-10-28 11:26 UTC, VascoPi commented on src/rprblender/properties/render.py
> +        has_multimaterial_object = next((True for i in bpy.context.scene.objects if len(i.material_slots) > 1), False)
Improved condition for material slots for RPRContextHybridPro.

2022-10-28 13:59 UTC, bsavery approved these changes

2022-10-28 20:37 UTC, ARozghon approved these changes
Approved by QA

2022-10-31 08:17 UTC, bnagirniak approved these changes
Looks good

2022-10-31 11:40 UTC, merged