RPRBLND-2255: Update toon shader to switch between 1/3/5 color modes.
GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon pull request #589
Opened 2023-03-09 12:36 UTC by VascoPi

### PURPOSE
Update toon shader to switch between 1/3/5 color modes.

### EFFECT OF CHANGE
You can now choose between three out of five color ramp modes by selecting the Ramp Mode dropdown list.
![image](https://user-images.githubusercontent.com/42581166/224024418-f157a926-4f3f-4a97-bb1e-f736ba0e288c.png)

### TECHNICAL STEPS
Added enum property "ramp_mode" with values THREE_COLORS, FIVE_COLORS. Adjusted code to support "ramp_mode" values.
Assign node width 310.0 if Advanced is enabled otherwise 140.

2023-03-09 22:53 UTC, bsavery requested changes
I would remove the advanced button.  

Make the drop down three items - 1 color, 3 color and 5 color.  Linked light always visible and mid color as albedo visible with 3 or 5 mode.

2023-03-10 09:41 UTC, ARozghon approved these changes
Approved by QA

2023-03-10 10:42 UTC, VascoPi commented
Updated pull request with requested changes.
Updated pull request description with new node look.

2023-03-10 15:02 UTC, DagerD approved these changes

2023-03-10 15:20 UTC, merged