RPRBLND-2301: Fix addon enabling in Blender 4.0+
GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon pull request #660
Opened 2023-11-08 19:25 UTC by VascoPi

### PURPOSE
Fix addon enabling in Blender 4.0+

### EFFECT OF CHANGE
Initial support for Blender 4.0+

### TECHNICAL STEPS
Adjusted node categories registration.
Adjusted ShaderNodeBsdfPrincipled.
Refactored sockets from NodeSocketInterface  to NodeTreeInterfaceSocket

### NOTES FOR REVIEWERS
Blender 4.0 known issues:
Render passes don't work properly.
Viewport render requires migration to GPU API instead of OpenGL

2023-11-23 12:51 UTC, bnagirniak requested changes

2023-11-23 12:51 UTC, bnagirniak commented on src/rprblender/engine/viewport_engine.py
> +        self.gl_texture.clear()
do we need to call `clear()`?

2023-11-23 12:51 UTC, bnagirniak commented on src/rprblender/nodes/__init__.py
> +RPR_NODES = {'shader': (rpr_nodes.RPRShaderNodeUber,
assign this to node_categories:
```
if BLENDER_VERSION >= "4.0":
    node_categories = {...}
else:
    node_categories = [...]
```

2023-11-23 12:51 UTC, bnagirniak commented on src/rprblender/engine/render_engine.py
> +                p.rect = image.reshape(len(p.rect), -1)
`foreach_set` should be used

2023-11-23 12:58 UTC, bnagirniak requested changes

2023-11-23 12:58 UTC, bnagirniak commented on src/rprblender/utils/gl.py
>  import sys
Remove `gl` module load

2023-11-23 20:16 UTC, bnagirniak approved these changes
Tested - works good, Added small code improvements.

2023-11-27 09:15 UTC, ARozghon approved these changes
Approved by QA

2023-12-30 02:22 UTC, merged