RPR Test Script
GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon pull request #686
Opened 2024-06-21 22:16 UTC by spenceau

### PURPOSE
Test Script to automate testing for RPR Blender Plug-in

### EFFECT OF CHANGE
final_render.py to generate Final Render in background
compare_render.py to compare Final Render with Ground Truth using Pixel Wise MSE and SSIM
viewport_render.py to generate Viewport Render (using final as specified) via opening Blender in foreground
test_script.ps1 to automate all 3 steps for a Single Scene and Blender Version 

this is stored within cmd_tools/test_script

### TECHNICAL STEPS
first commit; see README

### NOTES FOR REVIEWERS
Notes, if needed.

2024-07-26 12:08 UTC, feniksa commented on cmd_tools/test_script/viewport_render.py
> +    # import bpy
I think, it is possible to drop this comment as argparse used below.

2024-08-02 04:22 UTC, odil24 commented
@spenceau What PR does?

2024-08-07 12:27 UTC, feniksa approved these changes

2024-08-07 23:14 UTC, takahiroharada requested changes
Keep the changes minimum. SDK update shouldn't be in this PR. If needed, we need to do in another PR. Please do review all the changes and remove unnecessary files from this PR.

2024-08-07 23:14 UTC, takahiroharada commented on build.cmd
> +	python build.py
Why? we shouldn't do these changes. Let's keep explicit python versioning.

2024-08-08 22:25 UTC, spenceau commented
Changed to merge fork into the RPRBLD-0-test-script

2024-12-17 14:46 UTC, closed without merging